

services:
  postgresql : 
    image : postgres:13-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: youcode_02_01
    ports: ["5432:5432"]
    volumes:
      - ./load/postgresql_volume:/var/lib/postgresql/data